<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6zeVoa2' shared service.

return $this->privates['.service_locator.6zeVoa2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'passwordEncoder' => '?',
    'validator' => '?',
]);
