<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2J8Bzsy' shared service.

return $this->privates['.service_locator.2J8Bzsy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\API\\EditProfileControllerApi::index' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\API\\RegistrationControllerApi::register' => ['privates', '.service_locator.6zeVoa2', 'get_ServiceLocator_6zeVoa2Service.php', true],
    'App\\Controller\\API\\SecurityControllerApi::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\API\\SessionAdministrationControllerApi::cancelSession' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\EditProfileController::index' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\SessionAdministrationController::cancelSession' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\API\\EditProfileControllerApi:index' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\API\\RegistrationControllerApi:register' => ['privates', '.service_locator.6zeVoa2', 'get_ServiceLocator_6zeVoa2Service.php', true],
    'App\\Controller\\API\\SecurityControllerApi:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\API\\SessionAdministrationControllerApi:cancelSession' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\EditProfileController:index' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\SessionAdministrationController:cancelSession' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
], [
    'App\\Controller\\API\\EditProfileControllerApi::index' => '?',
    'App\\Controller\\API\\RegistrationControllerApi::register' => '?',
    'App\\Controller\\API\\SecurityControllerApi::login' => '?',
    'App\\Controller\\API\\SessionAdministrationControllerApi::cancelSession' => '?',
    'App\\Controller\\EditProfileController::index' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SessionAdministrationController::cancelSession' => '?',
    'App\\Controller\\API\\EditProfileControllerApi:index' => '?',
    'App\\Controller\\API\\RegistrationControllerApi:register' => '?',
    'App\\Controller\\API\\SecurityControllerApi:login' => '?',
    'App\\Controller\\API\\SessionAdministrationControllerApi:cancelSession' => '?',
    'App\\Controller\\EditProfileController:index' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SessionAdministrationController:cancelSession' => '?',
]);
