<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8z2fL1H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8z2fL1H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8z2fL1H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8z2fL1H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8z2fL1H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8z2fL1H',
    'container.build_id' => 'e88291d2',
    'container.build_time' => 1572554718,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8z2fL1H');
