<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oHXyyai' shared service.

return $this->privates['.service_locator.oHXyyai'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'utils' => ['services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true],
], [
    'utils' => '?',
]);
